language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo add-apt-repository ppa:pitti/systemd-semaphore -y
  - sudo apt-get -qq update
  - sudo apt-get install -y intltool gperf libcap-dev libmount-dev libmount1 realpath libsystemd-dev
env: TARGET_ARCH=x86_64 TARGET_VENDOR=-unknown TARGET_OS=linux-gnu FEATURES=bus
matrix:
  allow_failures:
    - rust: nightly
